export const PRODUCT_lIST = "PRODUCT_lIST";

export const PRODUCT_LIST_FETCHING = "PRODUCT_LIST_FETCHING";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";

export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";

export const CLICK ="CLICK";
export const REMOVEFROMCART ="REMOVEFROMCART";